config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :projections, only: [:new, :create, :show, :index, :edit, :update]
  resources :bookings, only: [:create]
  resources :users, only: [:show, :edit, :update]
  resources :reviews, only: [:create, :update]

  root to: 'pages#home'
  # For attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :projection
  belongs_to :user

  #TODO: check validity of has_one with ta
  has_one :review

  #validations
  validates :user, uniqueness: { scope: :projection, message: "You already participate to this event" }
end

app/models/projection.rb
class Projection < ApplicationRecord
  # Attachinary
  has_attachment :photo

  # Geocoding
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # Associations
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  # Validations
  validates :date, presence: {message: "The projection needs a date"}
  validates :address, presence: {message: "The projection needs an address"}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  # TODO: belongs_to :user

  #validations

  validates :rating, inclusion: {in: 0..5}
  validates :content, length: {minimum: 40, message: "Your review must be at least 40 characters long"}

  # def projection
  #   booking.projection
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Associations
  has_many :projections, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings

  # Attachinary
  has_attachment :photo

  # validations
  # Devise validates password and email --> can't be blank

  validates :first_name, presence: {message: "You must enter a first name"}

  # send welcome mail
  # after_create :send_welcome_email

  private

  # send welcome mail
  # def send_welcome_email
  #   UserMailer.welcome(self).deliver_now
  #   # Gildas says "don't really know what and where is deliver_now method"
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def store_current_location
    store_location_for(:user, request.url)
  end

  def after_sign_in_path_for(resource_or_scope)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :birth_date])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    url = params[:booking][:url]
    @booking = Booking.new(status: "accepted")
    @booking.user = current_user
    projection = Projection.find(params[:booking][:projection_id])
    @booking.projection = projection
    @booking.save
    redirect_to url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/projections_controller.rb
class ProjectionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    today = Date.today
    @projections = Projection.where("date >= ?", today).order(date: :desc)
    if params[:search].nil?
      @proposed_projections = @projections
      @found_projections = []
    else
      @query_location = params[:search][:location]
      if !(params[:search].nil?)
        @found_projections = Projection.near(@query_location, 50)

        if @found_projections.empty?
          @proposed_projections = @projections
        end

        @searched_location = @query_location

        if result_geocoder = Geocoder.search(@searched_location).first
          if hash_locality = result_geocoder.address_components.find { |item| item["types"].first == "locality"  }
              @searched_location = hash_locality["long_name"]
          end
        end
      else
        @proposed_projections = @projections
      end
    end

    @new_booking = Booking.new
  end

  def show
    set_projections
    @reviews = @projection.reviews
    @new_review = Review.new
    @new_booking = Booking.new
  end

  def new
    @projection = Projection.new
  end

  def create
    @projection = Projection.new(projection_params)
    @projection.user = current_user
    if @projection.save
      booking = Booking.create(projection: @projection, user: current_user, status: "accepted")
      redirect_to projection_path(@projection)
    else
      render :new
    end
  end

  def edit
    set_projections
  end

  def update
    set_projections
    if @projection.update(projection_params)
      redirect_to projection_path(@projection)
    else
      render :edit
    end
  end

  private

  def set_projections
    @projection = Projection.find(params[:id])
  end

  def projection_params
    params.require(:projection).permit(:name, :address, :movie, :date, :capacity, :photo)
  end

  # def clean_query_string

  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(content: params[:review][:content],rating: params[:review][:rating])
    booking = Booking.find(params[:review][:booking_id])
    @review.booking = booking
    @review.save
    redirect_to projection_path(booking.projection)
  end
  def update
    @review = Review.find(params[:review][:id])
    booking = Booking.find(params[:review][:booking_id])
    @review.content = params[:review][:content]
    @review.rating = params[:review][:rating]
    @review.booking = booking
    redirect_to projection_path(booking.projection)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
    @user = User.find(params[:id])
    @user_age_in_years = age(@user.birth_date)

    # raise to check date.today format
    @future_projections= @user.projections.where("date >= ?", Date.today).order(date: :desc)
    @past_projections= @user.projections.where("date < ?", Date.today).order(date: :desc)

    # Loop to get the projections & remove duplicate projections
    @future_bookings = []
    @user.bookings.all.each do |booking|
      (@future_bookings << booking.projection) if (booking.projection.date >= Date.today)
    end
    @future_bookings.reject! {|projection| @future_projections.include?(projection)}

    @past_bookings = []
    @user.bookings.all.each do |booking|
      (@past_bookings << booking.projection) if (booking.projection.date < Date.today)
    end
    @past_bookings.reject! {|projection| @past_projections.include?(projection)}


    # activity sets
    @future_activity= [@future_projections, @future_bookings].flatten
    @past_activity = [@past_projections, @past_bookings].flatten

    # helper
    @user.first_name.capitalize!
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birth_date, :projections, :email, :photo)
  end

  def age(birth_date)
    now = Time.now.utc.to_date
    now.year - birth_date.year - ((now.month > birth_date.month || (now.month == birth_date.month && now.day >= birth_date.day)) ? 0 : 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def resource_name
  :user
end

def resource
  @resource ||= User.new
end

def devise_mapping
 @devise_mapping ||= Devise.mappings[:user]
end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/projections_helper.rb
module ProjectionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(168, 132, 0, 0.31) 0%, rgba(61, 21, 0, 0.2) 50%), url(<%= image_path 'rooftop_projection.jpg' %>);">
  <div class="banner-content">
    <h1>Flix'n'Chill</h1>
    <p>Enjoy the best of Netflix in the best fucking places</p>
    <%= render "./projections/search-form" %>
  </div>
</div>

app/views/projections/_projection-index.html.erb
<div class="projection-card">
  <div class="movie">

    <div class="movie-image"
    <% if projection.photo? %>
    style="background-image: linear-gradient(-225deg, rgba(168, 132, 0, 0.31) 0%, rgba(61, 21, 0, 0.2) 50%), url(' <%= cl_image_path projection.photo.path, width: 230, height: 130, crop: :fill %> ');"
    <% else %>
    style="background-image: linear-gradient(-225deg, rgba(168, 132, 0, 0.31) 0%, rgba(61, 21, 0, 0.2) 50%), url('#');"
    <% end %>
    >

      <div class="movie-date text-center">
        <p><%= Date::ABBR_MONTHNAMES[projection.date.month] %></p>
        <p><%= projection.date.day %></p>
      </div>
      <h2><%= projection.movie.upcase %></h2>
    </div>
  </div>
  <div class="projection">
    <div class="projection-details">
      <div class="title"><%= link_to projection.name, projection_path(projection), class: "light-hover" %></div>
      <p><%= link_to projection.address, "https://www.google.fr/maps/search/#{projection.address}", target: "_blank"  %></p>
      <div class="participants">
        <% if !projection.bookings.empty? %>
          <% projection.bookings[0..5].each do |booking| %>
            <% if !booking.user.photo? %>
              <%= link_to user_path(booking.user) do %>
                <%= image_tag "https://www.drupal.org/files/profile_default.jpg", class: "avatar-large" %>
              <% end %>
            <% else %>
             <%= link_to user_path(booking.user) do %>
              <%= cl_image_tag booking.user.photo.path, height: 150, width: 150, crop: :fill, class: "avatar-large" %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
        <div>
          <%= "#{projection.capacity - projection.bookings.length} spots remaining" %>
        </div>
      </div>
    </div>
      <%= link_to "https://www.google.fr/maps/search/#{projection.address}", target: "_blank", class: "map-projection" do %>
        <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=214x160&sensor=false&maptype=roadmap&markers=color:red|#{projection.address}&key=AIzaSyBDgyF0G_Lqwti0wPDWzT6UmWkztTQPcoM" %>
      <span>Show directions</span>
    <% end %>
  </div>
  <div class="booking text-center">
    <h2><!-- TODO: projection.start_time -->20:00</h2>
    <% if user_signed_in? %>
      <% if projection.user_id == current_user.id %>
        <%= link_to "Edit" , edit_projection_path(projection), class: 'btn btn-default' %>
      <% elsif (projection.bookings & current_user.bookings).empty? %>
        <%= simple_form_for @new_booking do |f| %>
          <%= f.input :projection_id, as: :hidden, input_html: { value: projection.id } %>
          <%= f.input :url, as: :hidden, input_html: { value: request.original_url } %>
          <%= f.button :submit, "Participate", class:"btn btn-default" %>
        <% end %>
      <% else %>
        <p>Ticket taken !</p>
      <% end %>
    <% else %>
      <a href="#" class="btn btn-default" data-toggle="modal" data-target=".sign-up-modal">Sign up to join</a>
    <% end %>
  </div>
</div>

app/views/projections/_search-form.html.erb
<%= simple_form_for :search, url: projections_path, method: :get, html: { class: "form-inline", id: "search" } do |f| %>
    <% if @query_location.nil? %>
    <%= f.input :location, html5: true, placeholder: "Choose a city...", label: false, input_html: { class: "input-lg", id: "search-input" } %>
    <% else %>
    <%= f.input :location, html5: true, placeholder: "Choose a city...", label: false, input_html: { class: "input-lg", id: "search-input", value: @query_location }%>
    <% end %>
    <%= f.input :first_day, as: :hidden, html5: true, label: false  %>
    <%= f.input :last_day, as: :hidden, html5: true, label: false  %>
    <%= f.submit "Search", class: "btn btn-danger btn-lg", id: "search-submit" %>
<% end %>

app/views/projections/show.html.erb
<div class="banner banner-smaller" style="background-image: linear-gradient(-225deg, rgba(168, 132, 0, 0.31) 0%, rgba(61, 21, 0, 0.2) 50%), url(<%= image_path 'rooftop_projection.jpg' %>);"></div>
  <div class="container">
    <div class="row" id="projection">
      <div class="col-xs-12 col-sm-2 col-sm-offset-1 text-center">

        <% if @projection.photo? %>
          <div>
          <%= cl_image_tag @projection.photo.path, width: 160, height: 240, crop: :fill, id: "margin-image" %>
          </div>
          <% if user_signed_in?  %>
            <% if @projection.user_id == current_user.id %>
              <%= link_to "Edit" , edit_projection_path(@projection), class: 'btn btn-default', style: "margin-top: 20px"%>
            <% elsif (@projection.bookings & current_user.bookings).empty? %>
                <%= simple_form_for @new_booking do |f| %>
                <%= f.input :projection_id, as: :hidden, input_html: { value: @projection.id } %>
                <%= f.input :url, as: :hidden, input_html: { value: request.original_url } %>
                <%= f.button :submit, "Participate", class:"btn btn-danger", style: "margin-top: 20px" %>
              <% end %>
            <% else %>
              <p style="margin-top: 20px;">Ticket taken !</p>
            <% end %>
          <% else %>
            <a href="#" class="btn btn-default spaced" data-toggle="modal" data-target=".sign-up-modal">Sign up to join</a>
          <% end %>

        <% end %>
          <h4>Sits left:</h4>
          <%= @projection.capacity - @projection.bookings.length %>
      </div>
      <div class="col-xs-12 col-sm-8">
        <h2>
          <%= @projection.name %>
          <% if !@projection.user.photo? %>
          <%= image_tag "https://www.drupal.org/files/profile_default.jpg", class: "avatar-large" %>
          <% else %>
          <%= cl_image_tag @projection.user.photo.path, height: 150, width: 150, crop: :fill, class: "avatar-large" %>
          <% end %>
        </h2>
        <%= link_to "All projections", projections_path, class: " btn-medium" %>
        <h3>Event <h4><%= @projection.date.day.to_s + " " %><%= Date::ABBR_MONTHNAMES[@projection.date.month] %>
        </h4></h3>
        <br>
        <h4><%= @projection.address %></h4><%= link_to "Show map", "#", class: "btn-medium" %>
        <div class="show-map hidden ">
          <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=15&size=214x160&sensor=false&maptype=roadmap&markers=color:red|#{@projection.address}&key=AIzaSyBDgyF0G_Lqwti0wPDWzT6UmWkztTQPcoM" %>
        </div>

        <div class="participants">
          <h4 style="padding-right: 20px;">Capacity: <%= @projection.capacity %></h4>
          <h4 style="padding-right: 20px;">Participants: </h4>
          <% @projection.bookings.each do |booking| %>
            <% if !booking.user.photo? %>
            <%= image_tag "https://www.drupal.org/files/profile_default.jpg", class: "avatar-large" %>
            <% else %>
            <%= cl_image_tag booking.user.photo.path, height: 150, width: 150, crop: :fill, class: "avatar-large" %>
            <% end %>
          <% end %>
        </div>
        <h3>Reviews</h3>
        <div id="reviews">
          <ul class="list-group">
            <% if user_signed_in? %>
              <% if (@projection.reviews & current_user.reviews).empty? && !(@projection.bookings & current_user.bookings).empty? %>
                <li class="review-form list-group-item">
                  <%= simple_form_for @new_review do |f| %>
                    <%= f.error_notification %>
                    <% @booking = Booking.where(user: current_user, projection: @projection).first %>
                    <%= f.input :booking_id, as: :hidden, input_html: { value: @booking.id } %>
                    <%= f.input :content %>
                    <%= f.input :rating %>
                    <%= f.button :submit, "Review" %>
                  <% end %>
                </li>
              <% end %>
            <% end %>
            <% @reviews.each do |review| %>
              <li class="review list-group-item">
                <ul class="review list-group">
                  <li class="list-group-item">
                  <%= review.booking.user.first_name + " " + review.booking.user.last_name %>
                  <% if !review.booking.user.photo? %>
                  <%= image_tag "https://www.drupal.org/files/profile_default.jpg", class: "avatar-large" %>
                  <% else %>
                  <%= cl_image_tag review.booking.user.photo.path, height: 150, width: 150, crop: :fill, class: "avatar-large" %>
                  <% end %>
                  </li>
                  <li class="list-group-item"><%= review.created_at %></li>
                  <% if user_signed_in? && review.booking.user == current_user %>
                    <li class="review-form list-group-item">
                      <%= simple_form_for review do |f| %>
                        <%= f.error_notification %>
                        <%= f.input :id, as: :hidden, input_html: { value: review.id } %>
                        <% @booking = Booking.where(user: current_user, projection: @projection).first %>
                        <%= f.input :booking_id, as: :hidden, input_html: { value: @booking.id } %>
                        <%= f.input :content %>
                        <%= f.input :rating %>
                        <%= f.button :submit, "Edit review" %>
                      <% end %>
                    </li>
                  <% else %>
                    <li class="list-group-item"><%= review.content %></li>
                    <li class="list-group-item"><%= "X" * review.rating %></li>
                  <% end %>
                </ul>
                </br>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_home-navbar.html.erb
<div class="navbar-wagon-transparent">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <i class="fa fa-film" aria-hidden="true" style="color: white;
    font-size: 30px; "></i>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">


    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <% link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
         <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">

        <div class="dropdown">
          <% if current_user.photo? %>
          <%= cl_image_tag current_user.photo.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag "Underwood-placeholder.jpg", class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to projections_path do %>
                <i class="fa fa-ticket"></i>  <%= t(".profile", default: "All projections") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <a href="#" class="btn-underline navbar-wagon-item" data-toggle="modal" data-target=".log-in-modal">Log in</a>

      <%= render 'shared/login-modal' %>

      <!-- Sign up text link -->

      <a href="#" class="btn-underline navbar-wagon-item" data-toggle="modal" data-target=".sign-up-modal">Sign up</a>


      <%= render 'shared/signup-modal' %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_login-modal.html.erb
<div class="modal fade log-in-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-sm" role="document">
          <div class="modal-content">
          <h3 class="text-center">Log in</h3>
            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="form-inputs">
                <%= f.input :email, required: false, autofocus: true %>
                <%= f.input :password, required: false %>
                <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
              </div>

              <div class="form-actions text-center">
                <%= f.button :submit, "Log in", class: "btn btn-danger"%>
            <% end %>
                <br>
              <%= link_to "Forgot your password?", new_password_path(resource_name) %>
              </div>
          </div>
      </div>
      </div>

app/views/shared/_main-navbar.html.erb
<div class="navbar-wagon-opaque">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <i class="fa fa-film" aria-hidden="true" style="color: black;
    font-size: 30px; "></i>
  <% end %>



<!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
   <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo? %>
          <%= cl_image_tag current_user.photo.path, class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag "Underwood-placeholder.jpg", class: "avatar-large dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to projections_path do %>
                <i class="fa fa-ticket"></i>  <%= t(".profile", default: "All Projections") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

      <%= link_to "Add a projection", new_projection_path, class: "btn-medium" %>

      <% else %>

      <!-- Login text link -->
      <a href="#" class="navbar-wagon-link navbar-wagon-item" data-toggle="modal" data-target=".log-in-modal">Log in</a>

      <%= render 'shared/login-modal' %>

      <!-- Sign up text link -->

      <a href="#" class="navbar-wagon-link navbar-wagon-item" data-toggle="modal" data-target=".sign-up-modal">Sign up</a>

      <%= render 'shared/signup-modal' %>

    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_signup-modal.html.erb
<div class="modal fade sign-up-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-sm" role="document">
          <div class="modal-content">
          <h3 class="text-center">Sign up</h3>
           <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= f.error_notification %>

          <!-- TODO: Birth date issue -->
          <div class="form-inputs">
            <%= f.input :first_name, required: true, autofocus: true %>
            <%= f.input :last_name, required: true %>
            <%= f.input :birth_date, required: true, as: :date, end_year: Date.today.year - 90,
                              order: [:day, :month, :year] %>
            <%= f.input :email, required: true %>
            <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
            <%= f.input :password_confirmation, required: true %>
          </div>

          <div class="form-actions text-center" >
            <%= f.button :submit, "Sign up", class: "btn btn-danger btn-lg" %> <br>
        <% end %>
          </div>
          </div>
      </div>
      </div>

app/views/users/show.html.erb
<div class="container padded">
    <div class="row">
    <!-- user info -->
      <div class="col-xs-12 col-sm-3 col-sm-offset-1 text-center profile-tab overline">
        <!-- Profile photo -->
        <div>
          <% if @user.photo? %>
            <%= cl_image_tag @user.photo.path, height: 150, width: 150, crop: :fill, class: "avatar-xt-large" %>
          <% else %>
            <%= image_tag "Underwood-placeholder.jpg", height: 150, width: 150, crop: :fill, class: "avatar-xt-large" %>
          <% end %>
        </div>
          <!-- Profile Age and Name -->
          <h4 class="absolute-bottom"><%= @user.first_name %></h4>
          <p><%= @user_age_in_years %> years old</p>
          <% if current_user == @user %>
            <%= link_to edit_user_path(current_user), class: "btn btn-default absolute-bottom" do %>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %>
          <% end %>
      </div>

      <!-- Projection info -->
      <div class="col-xs-12 col-sm-8 projection-scroll">
        <div class="tab">
      <!-- Header -->
          <% if current_user == @user %>
           <h1 class="overline active" id="future-activity">My projections</h1>
          <% else %>
            <h1 class="overline active" id="future-activity"> <%= @user.first_name %>'s projections</h1>
          <% end %>
          <h1 class="overline" id="activity-history">Past projections</h1>
        </div>
        <div class="" id= "future-projections">
        <% if @future_activity.empty? %>
          <%= link_to "Add a projection", new_projection_path, class: "navbar-wagon-item navbar-wagon-button " %>
        <% else %>
        <!-- Future projection list -->
        <% @future_projections.each do |projection| %>
          <%# TODO: move partial to shared folder %>
          <%= render "projections/projection-index", projection: projection %>
        <% end %>

        <% @future_bookings.each do |projection| %>
          <%# TODO: move partial to shared folder %>
          <%= render "projections/projection-index", projection: projection %>
        <% end %>
        <% end %>
        </div>

        <div class="hidden" id="past-projections">
         <% if @past_activity.empty? %>
            <p class="text-center">No activity ! </p>
          <% else %>
          <!-- past projection list -->
          <% @past_projections.each do |projection| %>

            <%# TODO: move partial to shared folder %>
            <%= render "projections/projection-index", projection: projection %>
          <% end %>

          <% @past_bookings.each do |projection| %>
            <%# TODO: move partial to shared folder %>
            <%= render "projections/projection-index", projection: projection %>
          <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>